$(document).ready(function() {
    let feministArray = [
        '&ldquo;There are two ways of spreading light: to be the candle or the mirror that reflects it.&rdquo; <br /> &mdash;Edith Wharton',
        '&ldquo;No one can make you feel inferior without your consent.&rdquo; <br /> &mdash;Eleanor Roosevelt',
        '&ldquo;One child, one teacher, one pen and one book can change the world.&rdquo; <br /> &mdash;Malala Yousafzai',
        '&ldquo;I don&rsquo;t want other people to decide who I am. I want to decide that for myself.&rdquo; <br /> &mdash;Emma Watson',
        '&ldquo;Gentle ladies, you will remember till old age what we did together in our brilliant youth!&rdquo; <br /> &mdash;Sappho',
        '&ldquo;We all have our imperfections. But I&rsquo;m human, and you know, it&rsquo;s important to concentrate on other qualities besides outer beauty.&rdquo; <br /> &mdash;Beyonce',
        '&ldquo;Try to be a rainbow in someone&rsquo;s cloud.&rdquo; <br /> &mdash;Maya Angelou',
        '&ldquo;Use each interaction to be the best, most powerful version of yourself.&rdquo; <br /> &mdash;Marianne Williamson',
        '&ldquo;You have to believe in yourself when no one else does &ndash; that make you a winner right there.&rdquo; <br /> &mdash;Venus Williams',
        '&ldquo;The control and understanding of our personal fears is one of the most important undertakings of our lives.&rdquo; <br /> &mdash;Helen Mirren',
        '&ldquo;If I waited for perfection&hellip;I would never write a word.&rdquo; <br /> &mdash;Margaret Atwood',
        '&ldquo;Women are the largest untapped reservoir of talent in the world.&rdquo; <br /> &mdash;Hillary Clinton',
        '&ldquo;Life appears to me too short to be spent in nursing animosity, or registering wrongs.&rdquo; <br /> &mdash;Charlotte Bronte',
        '&ldquo;Never regret. If it&rsquo;s good, it&rsquo;s wonderful. If it&rsquo;s bad, it&rsquo;s experience.&rdquo; <br /> &mdash;Eleanor Hibbert',
        '&ldquo;I think you should take your job seriously, but not yourself &ndash; that is the best combination.&rdquo; <br /> &mdash;Judi Dench',
        '&ldquo;The important thing is not what they think of me, but what I think of them.&rdquo; <br /> &mdash;Queen Victoria',
        '&ldquo;I want to tell any young girl out there who&rsquo;s a geek, I was a really serious geek in high school. It works out.&rdquo; <br /> &mdash;Sheryl Sandberg',
        '&ldquo;Life is a succession of lessons which must be lived to be understood.&rdquo; <br /> &mdash;Helen Keller',
        '&ldquo;Everyone&rsquo;s dream can come true if you just stick to it and work hard.&rdquo; <br /> &mdash;Serena Williams',
        '&ldquo;I don&rsquo;t care what is written about me so long as it isn&rsquo;t true.&rdquo; <br /> &mdash;Dorothy Parker',
        '&ldquo;Each person must live their life as a model for others.&rdquo; <br /> &mdash;Rosa Parks',
        '&ldquo;My fears came true: people called me fat and hideous, and I lived. And now I keep living.&rdquo; <br /> &mdash;Lena Dunham',
        '&ldquo;I know I have the body but of a weak and feeble woman; but I have the heart and stomach of a king, and of a king of England too.&rdquo; <br /> &mdash;Queen Elizabeth I',
        '&ldquo;You don&rsquo;t get something for nothing and you have to work hard for what you want in life.&rdquo; <br /> &mdash;Sarah Storey',
        '&ldquo;If you don&rsquo;t like something, change it. If you can&rsquo;t change it, change your attitude. Don&rsquo;t complain.&rdquo; <br /> &mdash;Maya Angelou',
        '&ldquo;I would venture to guess that Anon, who wrote so many poems without signing them, was often a woman.&rdquo; <br /> &mdash;Virginia Woolf',
        '&ldquo;You&rsquo;re only young once, but you can be immature forever.&rdquo; <br /> &mdash;Germaine Greer',
        '&ldquo;Above all, be the heroine of your life, not the victim.&rdquo; <br /> &mdash;Nora Ephron',
        '&ldquo;The most common way people give up their power is by thinking they don&rsquo;t have any.&rdquo; <br /> &mdash;Alice Walker',
        '&ldquo;Every man I meet wants to protect me. I can&rsquo;t figure out what from.&rdquo; <br /> &mdash;Mae West',
        '&ldquo;Life is either a daring adventure or nothing.&rdquo; <br /> &mdash;Helen Keller',
        '&ldquo;A girl should be two things: who and what she wants.&rdquo; <br /> &mdash;Coco Chanel',
        '&ldquo;Somebody&rsquo;s negativity dumped on you is a bigger commentary on how they feel about themselves than you.&rdquo; <br /> &mdash;Kelly Ripa',
        '&ldquo;Take advantage of every opportunity that comes your way, with grace and humility. Be a sponge &ndash; and absorb and learn.&rdquo; <br /> &mdash;Chita Rivera',
        '&ldquo;Speak! It&rsquo;s a revolution for women to have voices.&rdquo; <br /> &mdash;Jill Soloway',
        '&ldquo;Don&rsquo;t play a supporting role in your own life.&rdquo; <br /> &mdash;Robin Roberts',
        '&ldquo;The trouble with some women is they get all excited about nothing &ndash; and then they marry him.&rdquo; <br /> &mdash;Cher',
        '&ldquo;A feminist is anyone who recognizes the equality and full humanity of women and men.&rdquo; <br /> &mdash;Gloria Steinem',
        '&ldquo;I do not wish [women] to have power over men; but over themselves.&rdquo; <br /> &mdash;Mary Wollstonecraft',
        '&ldquo;When a woman becomes her own best friend life is easier.&rdquo; <br /> &mdash;Diane Von Furstenberg',
        '&ldquo;Fitting in is boring. But it takes you nearly your whole life to work that out.&rdquo; <br /> &mdash;Clare Balding',
        '&ldquo;Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.&rdquo; <br /> &mdash;Marie Curie',
        '&ldquo;It&rsquo;s better to look ahead and prepare than to look back and regret.&rdquo; <br /> &mdash;Jackie Joyner-Kersee',
        '&ldquo;Treating women with respect should not be contingent on whether or not it &lsquo;gets you somewhere&rsquo;.&rdquo; <br /> &mdash;Lindy West',
        '&ldquo;You don&rsquo;t know a woman until you have had a letter from her.&rdquo; <br /> &mdash;Ada Leverson',
        '&ldquo;I never lose sight of the fact that just being is fun.&rdquo; <br /> &mdash;Katharine Hepburn',
        '&ldquo;In a time of destruction, create something.&rdquo; <br /> &mdash;Maxine Hong Kingston',
        '&ldquo;Love and kindness go hand in hand.&rdquo; <br /> &mdash;Marian Keyes',
        '&ldquo;Women, like men, should try to do the impossible. And when they fail, their failure should be a challenge to others.&rdquo; <br /> &mdash;Amelia Earhart',
        '&ldquo;One hour of right-down love is worth an age of dully living on.&rdquo; <br /> &mdash;Aphra Behn',
        '&ldquo;The more you practice, the better. But in any case, practice more than you play.&rdquo; <br /> &mdash;Babe Didrikson Zaharias',
        '&ldquo;Your victory is right around the corner. Never give up.&rdquo; <br /> &mdash;Nicki Minaj',
        '&ldquo;We are not interested in the possibilities of defeat; they do not exist.&rdquo; <br /> &mdash;Queen Victoria',
        '&ldquo;Dare to be as physically robust and varied as you always were.&rdquo; <br /> &mdash;Susie Orbach',
        '&ldquo;I don&rsquo;t focus on what I&rsquo;m up against. I focus on my goals and I try to ignore the rest.&rdquo; <br /> &mdash;Venus Williams',
        '&ldquo;Personal size and mental sorrow have certainly no necessary proportions. A large bulky figure has as good a right to be in deep affliction, as the most graceful set of limbs in the world.&rdquo; <br /> &mdash;Jane Austen',
        '&ldquo;Be brutally frank with yourself. It&rsquo;s safer.&rdquo; <br /> &mdash;Nellie Bly',
        '&ldquo;We are the hero of our own story.&rdquo; <br /> &mdash;Mary McCarthy',
        '&ldquo;We ask ourselves, &lsquo;Who am I to be brilliant, gorgeous, talented, fabulous?&rsquo; Actually, who are you not to be?&rdquo; <br /> &mdash;Marianne Williamson',
        '&ldquo;Many receive advice, only the wise profit from it.&rdquo; <br /> &mdash;Harper Lee',
        '&ldquo;Life shrinks or expands in proportion to one&rsquo;s courage.&rdquo; <br /> &mdash;Anais Nin',
        '&ldquo;Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.&rdquo; <br /> &mdash;Virginia Woolf',
        '&ldquo;It&rsquo;s about focusing on the fight and not the fright.&rdquo; <br /> &mdash;Robin Roberts',
        '&ldquo;It is not good to cross the bridge before you get to it.&rdquo; <br /> &mdash;Judi Dench',
        '&ldquo;Memories of our lives, of our works and our deeds will continue in others.&rdquo; <br /> &mdash;Rosa Parks',
        '&ldquo;Love largely and hate nothing. Hold no aim that does not chord with universal good.&rdquo; <br /> &mdash;Ella Wheeler Wilcox',
        '&ldquo;Obtain power, then, by all means; power is the law of man; make it yours.&rdquo; <br /> &mdash;Maria Edgeworth',
        '&ldquo;I think one&rsquo;s feelings waste themselves in words; they ought all to be distilled into actions, and into actions which bring results.&rdquo; <br /> &mdash;Florence Nightingale',
        '&ldquo;Real education should educate us out of self into something far finer; into a selflessness which links us with all humanity.&rdquo; <br /> &mdash;Nancy Astor',
        '&ldquo;It is the mind that makes the body.&rdquo; <br /> &mdash;Sojourner Truth',
        '&ldquo;Though he had Eden to live in, man cannot be happy alone.&rdquo; <br /> &mdash;Josephine Pollard',
        '&ldquo;You may not control all the events that happen to you, but you can decide not to be reduced by them.&rdquo; <br /> &mdash;Maya Angelou',
        '&ldquo;Not many men have both good fortune and good sense.&rdquo; <br /> &mdash;Marilyn French',
        '&ldquo;Don&rsquo;t spend time beating on a wall, hoping to transform it into a door.&rdquo; <br /> &mdash;Coco Chanel',
        '&ldquo;Don&rsquo;t be like anyone else. Find your voice, your script, your rhythms.&rdquo; <br /> &mdash;Jill Soloway',
        '&ldquo;Love is an indescribable sensation &ndash; perhaps a conviction, a sense of certitude.&rdquo; <br /> &mdash;Joyce Carol Oates',
        '&ldquo;That perfect tranquillity of life, which is nowhere to be found but in retreat, a faithful friend and a good library.&rdquo; <br /> &mdash;Aphra Behn',
        '&ldquo;Virtue can only flourish amongst equals.&rdquo; <br /> &mdash;Mary Wollstonecraft',
        '&ldquo;Energy rightly applied and directed will accomplish anything.&rdquo; <br /> &mdash;Nellie Bly',
        '&ldquo;A word after a word after a word is power.&rdquo; <br /> &mdash;Margaret Atwood',
        '&ldquo;Not knowing when the dawn will come, I open every door.&rdquo; <br /> &mdash;Emily Dickinson',
        '&ldquo;Feminism is the ability to choose what you want to do.&rdquo; <br /> &mdash;Nancy Reagan',
        '&ldquo;I am not afraid; I was born to do this.&rdquo; <br /> &mdash;Joan of Arc',
        '&ldquo;The first problem for all of us, men and women, is not to learn, but to unlearn.&rdquo; <br /> &mdash;Gloria Steinem',
        '&ldquo;Beauty is perfect in its imperfections, so you just have to go with the imperfections.&rdquo; <br /> &mdash;Diane Von Furstenberg',
        '&ldquo;There can be no happiness if the things we believe in are different from the things we do.&rdquo; <br /> &mdash;Freya Stark',
        '&ldquo;Nobility, without virtue, is a fine setting without a gem.&rdquo; <br /> &mdash;Jane Porter',
        '&ldquo;There is no cosmetic for beauty like happiness.&rdquo; <br /> &mdash;Marguerite Gardiner',
        '&ldquo;In science, all acts, no matter how trivial or banal, enjoy democratic equality.&rdquo; <br /> &mdash;Mary McCarthy',
        '&ldquo;You can&rsquo;t win them all &ndash; but you can try.&rdquo; <br /> &mdash;Babe Didrikson Zaharias',
        '&ldquo;All adventures, especially into new territory, are scary.&rdquo; <br /> &mdash;Sally Ride',
        '&ldquo;Your self-worth is defined by you. You don&rsquo;t have to depend on someone telling you who you are.&rdquo; <br /> &mdash;Beyonce',
        '&ldquo;Suddenly when one has almost made up one&rsquo;s mind to a certain action it casually throws an opportunity into one&rsquo;s path.&rdquo; <br /> &mdash;Eleanor Hibbert',
        '&ldquo;Do your thing and don&rsquo;t care if they like it.&rdquo; <br /> &mdash;Tina Fey',
        '&ldquo;The trick in life is learning how to deal with it.&rdquo; <br /> &mdash;Helen Mirren',
        '&ldquo;All I can do is follow my instincts, because I&rsquo;ll never please everyone.&rdquo; <br /> &mdash;Emma Watson',
        '&ldquo;There is no charm equal to tenderness of heart.&rdquo; <br /> &mdash;Jane Austen',
        '&ldquo;Give back in some way. Always be thoughtful of others.&rdquo; <br /> &mdash;Jackie Joyner-Kersee',
        '&ldquo;It is justice, not charity, that is wanting in the world.&rdquo; <br /> &mdash;Mary Wollstonecraft',
        '&ldquo;Be less curious about people and more curious about ideas.&rdquo; <br /> &mdash;Marie Curie',
        '&ldquo;Optimism can be relearnt.&rdquo; <br /> &mdash;Marian Keyes',
        '&ldquo;There must be a battle, a brave boisterous battle, with pennants waving and cannon roaring, before there can be peaceful treaties and enthusiastic shaking of hands.&rdquo; <br /> &mdash;Mary Elizabeth Braddon',
        '&ldquo;Cease telling other human beings what they &lsquo;should&rsquo; and &lsquo;shouldn&rsquo;t&rsquo; do with their bodies.&rdquo; <br /> &mdash;Lindy West',
        '&ldquo;Attitude is everything.&rdquo; <br /> &mdash;Diane Von Furstenberg',
        '&ldquo;I never hanker after the past &ndash; I prefer to devote myself to new tasks.&rdquo; <br /> &mdash;Steffi Graf',
        '&ldquo;If you obey all the rules, you miss all the fun.&rdquo; <br /> &mdash;Katharine Hepburn',
        '&ldquo;I declare to you that woman must not depend upon the protection of man, but must be taught to protect herself, and there I take my stand.&rdquo; <br /> &mdash;Susan B. Anthony',
        '&ldquo;In order to be irreplaceable one must always be different.&rdquo; <br /> &mdash;Coco Chanel',
        '&ldquo;If everything was perfect, you would never learn and you would never grow.&rdquo; <br /> &mdash;Beyonce',
        '&ldquo;I think if you feel like you were born to write, then you probably were.&rdquo; <br /> &mdash;Lena Dunham',
        '&ldquo;Nothing is impossible; the word itself says &lsquo;I&rsquo;m possible&rsquo;!&rdquo; <br /> &mdash;Audrey Hepburn',
        '&ldquo;Forgiveness is a virtue of the brave.&rdquo; <br /> &mdash;Indira Gandhi',
        '&ldquo;We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.&rdquo; <br /> &mdash;Marie Curie',
        '&ldquo;You can be strong and true to yourself without being rude or loud.&rdquo; <br /> &mdash;Paula Radcliffe',
        '&ldquo;We should all start to live before we get too old. Fear is stupid. So are regrets.&rdquo; <br /> &mdash;Marilyn Monroe',
        '&ldquo;I have learned over the years that when one&rsquo;s mind is made up, this diminishes fear.&rdquo; <br /> &mdash;Rosa Parks',
        '&ldquo;Whether women are better than men I cannot say &ndash; but I can say they are certainly no worse.&rdquo; <br /> &mdash;Golda Meir',
        '&ldquo;I am not bound to give reasons for what I do to anybody.&rdquo; <br /> &mdash;Lady Hester Stanhope',
        '&ldquo;Life-fulfilling work is never about the money &ndash; when you feel true passion for something, you instinctively find ways to nurture it.&rdquo; <br /> &mdash;Eileen Fisher',
        '&ldquo;The most effective way to do it is to do it.&rdquo; <br /> &mdash;Amelia Earhart',
        '&ldquo;You can stand tall without standing on someone. You can be a victor without having victims.&rdquo; <br /> &mdash;Harriet Woods',
        '&ldquo;Think like a queen. A queen is not afraid to fail. Failure is another stepping stone to greatness.&rdquo; <br /> &mdash;Oprah Winfrey',
        '&ldquo;Women need real moments of solitude and self-reflection to balance out how much of ourselves we give away.&rdquo; <br /> &mdash;Barbara De Angelis',
        '&ldquo;The great marriages are partnerships. It can&rsquo;t be a great marriage without being a partnership.&rdquo; <br /> &mdash;Helen Mirren',
        '&ldquo;The connections between and among women are the most feared, the most problematic, and the most potentially transforming force on the planet.&rdquo; <br /> &mdash;Adrienne Rich',
        '&ldquo;Some of us are becoming the men we wanted to marry.&rdquo; <br /> &mdash;Gloria Steinem',
        '&ldquo;They say that women talk too much. If you have worked in Congress you know that the filibuster was invented by men.&rdquo; <br /> &mdash;Clare Boothe Luce',
        '&ldquo;It is the ultimate luxury to combine passion and contribution. It&rsquo;s also a very clear path to happiness.&rdquo; <br /> &mdash;Sheryl Sandberg',
        '&ldquo;My choice, my responsibility. Win or lose, only I hold the key to my destiny.&rdquo; <br /> &mdash;Elaine Maxwell',
        '&ldquo;When the whole world is silent, even one voice becomes powerful.&rdquo; <br /> &mdash;Malala Yousafzai',
        '&ldquo;Yet if a woman never lets herself go, how will she ever know how far she might have got?&rdquo; <br /> &mdash;Germaine Greer',
        '&ldquo;I am no bird; and no net ensnares me; I am a free human being with an independent will.&rdquo; <br /> &mdash;Charlotte Bronte',
        '&ldquo;Taking joy in life is a woman&rsquo;s best cosmetic.&rdquo; <br /> &mdash;Rosalind Russell',
        '&ldquo;You only live once, but if you do it right, once is enough.&rdquo; <br /> &mdash;Mae West',
        '&ldquo;To succeed you have to believe in something with such a passion that it becomes a reality.&rdquo; <br /> &mdash;Anita Roddick',
        '&ldquo;Far away there in the sunshine are my highest aspirations. I may not reach them, but I can look up and see their beauty, believe in them, and try to follow where they lead.&rdquo; <br /> &mdash;Louisa May Alcott',
        '&ldquo;A woman with a voice is by definition a strong woman. But the search to find that voice can be remarkably difficult.&rdquo; <br /> &mdash;Melinda Gates',
        '&ldquo;How wonderful it is that nobody need wait a single moment before starting to improve the world.&rdquo; <br /> &mdash;Anne Frank',
        '&ldquo;There&rsquo;s power in looking silly and not caring that you do.&rdquo; <br /> &mdash;Amy Poehler',
        '&ldquo;I dwell in possibility.&rdquo; <br /> &mdash;Emily Dickinson',
        '&ldquo;The giving of love is an education in itself.&rdquo; <br /> &mdash;Eleanor Roosevelt',
        '&ldquo;You must first be who you really are, then do what you need to do, in order to have what you want.&rdquo; <br /> &mdash;Margaret Young',
        '&ldquo;Attempt the impossible in order to improve your work.&rdquo; <br /> &mdash;Bette Davis',
        '&ldquo;You can break that big plan into small steps and take the first step right away.&rdquo; <br /> &mdash;Indira Gandhi',
        '&ldquo;Never give up, for that is just the place and time that the tide will turn.&rdquo; <br /> &mdash;Harriet Beecher Stowe',
        '&ldquo;Forever is composed of nows.&rdquo; <br /> &mdash;Emily Dickinson',
        '&ldquo;Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.&rdquo; <br /> &mdash;Harriet Tubman',
        '&ldquo;Choose people who lift you up.&rdquo; <br /> &mdash;Michelle Obama'
    ]

    let feministQuotes = feministArray.sort(function(a,b) {
    	return 0.5 - Math.random()
    })

    let feministQuote = feministQuotes[0]

    let feminist = `<p>${feministQuote}</p>`

    $('#feminist').html(feminist)
})